[build-system]
requires = ["uv_build >= 0.12.10, <0.13.0"]
build-backend = "uv_build"


[project]
name = "piper-client"
requires-python = ">=3.12"
dependencies = [
    "pyAgxArm @ https://github.com/agilexrobotics/pyAgxArm.git",
    "numpy>=2.0.0,<2.3.0",
    "placo",
    "scipy",
    "websockets",
    "ischedule",
    "tyro",
    "opencv-python-headless>=4.9.0,<4.14.0",
    "zarr>=3.2.0",
    "rerun-sdk",
    "av",
]
version = "0.0.0"

[project.optional-dependencies]
dev = [
    "ruff",
    "ty",
    "mypy",
]


[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["stubs"]

[tool.ruff.lint]
select = [
    "E", "W", "F", "I", "ASYNC"
]
ignore = []


[tool.ty]

[tool.ty.analysis]
allowed-unresolved-imports = ["Boost.Python"]

[tool.ty.environment]
extra-paths = ["stubs"]
python-version = "3.12"
